In [31]:
#Define a function that takes three numbers as input parameters and returns the maximum of three numbers by using if-else statements and not using the max() function or any similar one.
# include a check whether the input values are indeed numbers. If incorrect output a message that tells the user what went wrong
# #print the result using a formatted print command

def numbers(num1,num2,num3):

  if not ((type(num1) is int or type(num1) is float) and \
          (type(num2) is int or type(num2) is float) and \
          (type(num3) is int or type(num3) is float)):
    return "Error: All inputs must be numbers"


  if num1 >= num2 and num1 >= num3:
    maximum = num1
  elif num2 >= num1 and num2 >= num3:
    maximum = num2
  else:
    maximum = num3


  print(f"The maximum of {num1}, {num2}, and {num3} is {maximum}")
  return maximum

numbers(1,2,3)
numbers(10, 5, 8)
numbers(-1, -5, 0)
numbers(4.5, 2.1, 7.8)


The maximum of 1, 2, and 3 is 3
The maximum of 10, 5, and 8 is 10
The maximum of -1, -5, and 0 is 0
The maximum of 4.5, 2.1, and 7.8 is 7.8


7.8

In [32]:
#Define a function that takes an integer number as an input parameter and checks wether the
#number is a prime number
#include a check whether the value is indeed an integer number. If incorrect output a
#message that tells the user what went wrong
#print the result using a formatted print command

import math

def param(integer):
  if integer == int(integer):
    if integer<2:
      print("It is not a prime number")
    elif integer==2:
      print("It is a prime number")
    elif integer%2==0:
      print("It is not a prime number")
    else:
        # Checking odd divisors up to the square root of the number
        limit = int(math.sqrt(integer)) + 1

        is_prime = True
        for i in range(3, limit, 2):
            if integer % i == 0:
                is_prime = False
                break

        if is_prime:
            print(f"The number {integer} is a prime number")
        else:
            print(f"The number {integer} is not a prime number")

  else:
    print("Error: I need a whole number (an integer) to check for primality")



param(2)
param(17)
param(15)
param(4.5)
param(-5)
param(24)


It is a prime number
The number 17 is a prime number
The number 15 is not a prime number
Error: I need a whole number (an integer) to check for primality
It is not a prime number
It is not a prime number


In [33]:
#Define a function that takes a string as an input parameter and checks wether the input string is a palindrom (a word or phrase that reads the same backward as it reads forward)
#include a check whether the value is indeed a string. If incorrect output a message that tells the user what went wrong
#print the result using a formatted print command

def palindrome(word):
  if word == str(word):
    if word == word[::-1]:
      print(f"The input {word} is a palindrome")
    else:
        print("The input is not a palindrome")
  else:
    print("The input is not a string")

palindrome(3)
palindrome("room")
palindrome("level")

The input is not a string
The input is not a palindrome
The input level is a palindrome


In [34]:
#Define a function that takes an integer number as an input parameter and checks wether the number is a prime number
# include a check whether the value is indeed an integer number. If incorrect output a message that tells the user what went wrong
#print the result using a formatted print command

def is_prime(n):

    if n <= 1:
        return False

    i = 2
    while i * i <= n:
        if n % i == 0:
            return False
        i += 1
    return True

count = 0  # No of primes found
number = 1 # Current integer
prime_100th = 0

# Looping until the 100th prime number is found
while count < 100:
    number += 1

    # Checking if the current number is prime
    if is_prime(number):
        count += 1
        prime_100th = number

print(f"The 100th prime number is: {prime_100th}")

The 100th prime number is: 541


In [35]:
#According to legend, the inventor of the chess game and board (8x8 squares) asked his ruler to pay him in rice grains, putting 1 grain on the first square and doubling the number of grains from one square field to the next (i.e. 1 on the first, 2 on the second, 4 on the third, 8 on the fourth square).
#Create a 2D, 8x8 array for the chess board squares. Use a nested for-loop to fill them with grains accordingly.
#How many rice grains will you end up with on the last square?
#Hint: Start with a smaller board, i.e. 3x3, and then go from there to a full chessboard

import numpy as np

Board_size = 8
Total_squares = Board_size * Board_size



chessboard = np.zeros((Board_size, Board_size), dtype=object) #data type is object because of very large numbers

current_grains = 1

total_grains = 0 # Lets keep it as zero for now

# Using for loops
for row in range(Board_size):
    for col in range(Board_size):

        chessboard[row, col] = current_grains
        total_grains += current_grains
        current_grains *= 2

last_square_grains = chessboard[Board_size - 1, Board_size - 1]

print(" Chessboard Grain Distribution,Here I am only showing the first 10 rows due to the size issue ")
print(chessboard[:10])
print(f"The total number of squares processed was: {Total_squares}")
print(f"The number of rice grains on the last square is: {last_square_grains}")

 Chessboard Grain Distribution,Here I am only showing the first 10 rows due to the size issue 
[[1 2 4 8 16 32 64 128]
 [256 512 1024 2048 4096 8192 16384 32768]
 [65536 131072 262144 524288 1048576 2097152 4194304 8388608]
 [16777216 33554432 67108864 134217728 268435456 536870912 1073741824
  2147483648]
 [4294967296 8589934592 17179869184 34359738368 68719476736 137438953472
  274877906944 549755813888]
 [1099511627776 2199023255552 4398046511104 8796093022208 17592186044416
  35184372088832 70368744177664 140737488355328]
 [281474976710656 562949953421312 1125899906842624 2251799813685248
  4503599627370496 9007199254740992 18014398509481984 36028797018963968]
 [72057594037927936 144115188075855872 288230376151711744
  576460752303423488 1152921504606846976 2305843009213693952
  4611686018427387904 9223372036854775808]]
The total number of squares processed was: 64
The number of rice grains on the last square is: 9223372036854775808
